### ISSUE TITLE
[BUG]: Printing directly to the debug console

### ISSUE THREAD

**Issue by hyperupcall** [mshr-h/vscode-verilog-hdl-support#289] opened 2022-06-06 17:24 UTC
**Describe the bug**
Launching any extension with this as a dependency will clutter the debug console

**Environment (please complete the following information):**
 - OS: Linux
 - VS Code version 1.67.2
 - Extension version 1.67.2
 - color themes, lint tools, etc: Any

**Steps to reproduce**
1. Run an extension in debug mode (in the image below, i'm using [mine](https://github.com/hyperupcall/vscode-hyperupcall), but any should do)
2. See debug console

**Log**
```sh
mshr-h.veriloghdl is now active!
ctags manager configure
Invalid linter name.
Invalid language server name.
```

**Expected behavior**
No output

**Actual behavior**

![image](https://user-images.githubusercontent.com/24364012/172212409-8251dac3-fd85-4482-b2c6-9ddf0eb59cff.png)

**Additional context**
Unfortunately, out of my 150+ installed extensions, this one is the only one that manually prints information to the debug console. The only other output is from an unintended error from a different extension. I see that there are a _lot_ of `console.log` scattered thoughout the codebase. Maybe it would be better to log informative output to a dedicated output window?

**Comment by mshr-h** [comment] 2022-12-12 01:52
It's not a bug but I understand it's annoying. Will fix.

**Comment by mshr-h** [comment] 2022-12-20 13:05
Should be fixed on v1.6.0.

**Comment by hyperupcall** [comment] 2022-12-21 06:39
thank you!

**Closed** 2022-12-21 06:40 UTC
Labels: bug
